language: perl

perl: 5.18

sudo: false

notifications:
  email: false

addons:
  apt:
    packages:
      - libpcre3-dev
      - build-essential

env:
  global:
    - OPENRESTY=1.11.2.2
    - DOWNLOAD_CACHE=$HOME/download-cache
    - INSTALL_CACHE=$HOME/install-cache

before_install:
  - source .ci/setup_openresty.sh
  - pip install --user hererocks
  - hererocks lua_install -r^ -l 5.1
  - export PATH=$PATH:$PWD/lua_install/bin
  - eval `luarocks path`
  - luarocks install luacheck
  - luarocks install luacov-coveralls

install:
  - luarocks make

script:
  - make lint
  - make coverage
  - luacov-coveralls -i lib/resty

cache:
  cpan: true
  apt: true
  pip: true
  directories:
    - $DOWNLOAD_CACHE
    - $INSTALL_CACHE
